/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package numberguessinggame;

import Classes.GuessNumbers;
import Classes.Gui;

/**
 *
 * @author yashr
 */
public class numbergame extends javax.swing.JFrame {

    /**
     * Creates new form numbergame
     */
    public numbergame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        l_guess = new javax.swing.JLabel();
        l_score = new javax.swing.JLabel();
        l_life = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        f_guess = new javax.swing.JTextField();
        l_showRandom = new javax.swing.JLabel();
        l_show = new javax.swing.JLabel();
        l_unshow = new javax.swing.JLabel();
        btn_newRandom = new javax.swing.JButton();
        btn_guess = new javax.swing.JButton();
        l_remarks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("*********Guessing Game*********");

        l_guess.setText("Guess: 0");

        l_score.setText("Score: 0");

        l_life.setText("Life: 10");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Enter Your number (1-100) :");

        f_guess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                f_guessKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                f_guessKeyTyped(evt);
            }
        });

        l_showRandom.setText("?");

        l_show.setText("Show");
        l_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_showMouseClicked(evt);
            }
        });

        l_unshow.setText("Hide");
        l_unshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_unshowMouseClicked(evt);
            }
        });

        btn_newRandom.setText("New Random Number");
        btn_newRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newRandomActionPerformed(evt);
            }
        });

        btn_guess.setText("Guess");
        btn_guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guessActionPerformed(evt);
            }
        });

        l_remarks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_remarks.setForeground(new java.awt.Color(204, 0, 255));
        l_remarks.setText("********************Try Your Luck :)********************");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(l_showRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_show, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_unshow, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_score)
                                .addGap(33, 33, 33)
                                .addComponent(l_guess, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(l_life))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(f_guess, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_remarks)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_newRandom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_guess)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_guess)
                    .addComponent(l_score)
                    .addComponent(l_life))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_guess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_showRandom)
                    .addComponent(l_show)
                    .addComponent(l_unshow))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_newRandom)
                    .addComponent(btn_guess))
                .addGap(21, 21, 21)
                .addComponent(l_remarks)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guessActionPerformed
        // TODO add your handling code here:
        guess();
    }//GEN-LAST:event_btn_guessActionPerformed

    private void btn_newRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newRandomActionPerformed
        // TODO add your handling code here:
        randomNew();
    }//GEN-LAST:event_btn_newRandomActionPerformed

    private void l_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_showMouseClicked
        // TODO add your handling code here:
        l_show.setEnabled(false);
        l_unshow.setEnabled(true);
        l_showRandom.setText(String.valueOf(random));
    }//GEN-LAST:event_l_showMouseClicked

    private void l_unshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_unshowMouseClicked
        // TODO add your handling code here:
        l_show.setEnabled(true);
        l_unshow.setEnabled(false);
        l_showRandom.setText("?");
    }//GEN-LAST:event_l_unshowMouseClicked

    private void f_guessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_guessKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_guessKeyPressed

    private void f_guessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_guessKeyTyped
        // TODO add your handling code here:
        Gui._integerOnly(evt);
    }//GEN-LAST:event_f_guessKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(numbergame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(numbergame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(numbergame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(numbergame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new numbergame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guess;
    private javax.swing.JButton btn_newRandom;
    private javax.swing.JTextField f_guess;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_guess;
    private javax.swing.JLabel l_life;
    private javax.swing.JLabel l_remarks;
    private javax.swing.JLabel l_score;
    private javax.swing.JLabel l_show;
    private javax.swing.JLabel l_showRandom;
    private javax.swing.JLabel l_unshow;
    // End of variables declaration//GEN-END:variables
    
    Gui gui;
    private int random = 0, bestScore = 0, yourScore = 0 ,addCorrectScore = 3;
    private byte guessCount = 0, LifeCount = 10, greaterThanError = 0, lessThanError = 0;
    
    private void init() {
        gui = new Gui();
        Gui._centerFrame(this);
        
        random = GuessNumbers._randomNumber();
        l_unshow.setEnabled(false);
        
//        bestScore = Gui.getCurrentBestScore();
//        l_bestscore.setText("Best Score: "+bestScore);
    }
    
    private void randomNew(){
        random = GuessNumbers._randomNumber();
        f_guess.setText("");
        f_guess.requestFocus();
        
        l_unshow.setEnabled(false);
        l_show.setEnabled(true);
        l_showRandom.setText("?");
    }
     
    private void guess(){
        // validate user input
        if(f_guess.getText().equals("")){
          Gui._message("Please enter your number:",0);
          f_guess.requestFocus();
        }
        else if (Integer.parseInt(f_guess.getText()) >= 101 || Integer.parseInt(f_guess.getText()) < 1){
            Gui._message("Please enter number from 1-100!", 0);
            f_guess.setText("");
            f_guess.requestFocus();
        }
        else{
            int yourNumber = Integer.parseInt(f_guess.getText());
            
            if(yourNumber == random){
                Gui._message("YOU WON!\nadditional 3 life was added!", 1);
                yourScore++; // Increment correct number
                l_score.setText("Score :"+yourScore);
                //add life
                LifeCount+=addCorrectScore;
                l_life.setText("Life: "+LifeCount);
            }
            else{
                LifeCount--;// Count the error 
                l_life.setText("Life: "+LifeCount);
                
                if(LifeCount == 0){
                    Gui._message("You used all your life. \nPlease try again next time !", 0);
                    System.exit(0);
                }
            }
            guessCount++;
            l_guess.setText("Guesses: "+guessCount);
        }
    }
    
}
